seed: 1024
data:
    dataset: hmdb51
    modality: RGB
    num_segments: 8
    seg_length: 1
    batch_size: 16
    workers: 1
    num_classes: 51
    image_tmpl: 'image_{:06d}.jpg'
    val_root: 'HMDB51_frame'
    val_list: 'lists/hmdb51/hmdb_full_for_zeroshot.txt'    
    label_list: 'lists/hmdb51_labels.csv'
    index_bias: 1
    input_size: 224
network:
    arch: ViT-L/14       #ViT-L/14  ViT-B/32 ViT-B/16
    init: True
    drop_out: 0.0
    emb_dropout: 0.0
    type: clip_hmdb
    sim_header: Transf
logging:
    print_freq: 10
    eval_freq: 1