pretrain:
resume:
seed: 1024
tome: 16
data:
    dataset: hmdb51
    modality: RGB
    num_segments: 16
    seg_length: 1
    batch_size: 4
    workers: 8
    num_classes: 51
    image_tmpl: 'image_{:06d}.jpg'
    train_root: '/data/video_dataset/hmdb51/frame'
    val_root: '/data/video_dataset/hmdb51/frame'
    train_list: 'lists/hmdb51/train_rgb_split_1.txt'
    val_list: 'lists/hmdb51/val_rgb_split_1.txt'
    label_list: 'lists/hmdb51_labels.csv'
    input_size: 224
    random_shift: True
network:
    arch: ViT-L/14  #ViT-B/32 ViT-B/16
    init: True
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_hmdb
    sim_header: Transf
    drop: 0      
solver:
    type: cosine
    epochs: 30
    start_epoch: 0
    optim: adamw
    lr: 5.e-5
    lr_warmup_step: 5
    weight_decay: 0.2
    loss_type: CE
    evaluate: False
    clip_ratio: 0.1
    grad_accumulation_steps: 2
logging:
    print_freq: 10
    eval_freq: 5